FROM python:3.9-slim

# Install Python libraries
RUN pip install boto3 pandas pyarrow requests openpyxl

# Create a directory for the database file
RUN mkdir -p /app/data

# Copy your Python script
COPY download_data.py /app/download_data.py

# Set the working directory
WORKDIR /app

# Command to run your script
CMD ["python", "download_data.py"]
